# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6cb577719f098469c7e63dbd3f113cba7b2fe09ba44a540441a669a46a6e139c4ebf81161d23a41a503349790bf7daa7cd4dcbca27fa063addb2f872e19d807

test:
  secret_key_base: 45c3c675df18aa3f3e95c03a5fe2e89babfece8afdf7f689ecdb6a67d51dcedccf2c9c4f73a3938cd24a6491a7cae710c2bc5a98a685a3445410fc813feb40aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
